version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"  # Mapeia a porta 5432 do container para a porta 5432 do host
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRES_DB=shortslinks
    volumes:
      - postgres_data:/bitnami/postgresql/data

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"  # Mapeia a porta 6379 do container para a porta 6379 do host
    environment:
      - REDIS_PASSWORD=docker
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  postgres_data:
  redis_data:
